### ISSUE TITLE
remove unnecessary pointer use

### ISSUE THREAD

**Issue by wangnengjie** [NickLee2050/hust_sat_solver_remake#2]
I see **all** shared_ptr in this project is unnecessary. I have tried to remove them. Below is the result.
![image](https://user-images.githubusercontent.com/43722125/157161104-7cb6a94f-cbf9-40e6-bf76-8aa8846b2b23.png)

time from 285ms to 230ms

by the way, most of the time, you should use unique_ptr instead of shard_ptr......

**Comment by NickLee2050** [comment]
WIP
